data_samples = {2018: {"tauTau": ["SKIM_Tau_Run2018A",
                                  "SKIM_Tau_Run2018B",
                                  "SKIM_Tau_Run2018C",
                                  "SKIM_Tau_Run2018D",],
                       "muTau": ["SKIM_SingleMuon_Run2018A",
                                 "SKIM_SingleMuon_Run2018B",
                                 "SKIM_SingleMuon_Run2018C",
                                 "SKIM_SingleMuon_Run2018D",],
                       "eTau": ["SKIM_EGamma_Run2018A",
                                "SKIM_EGamma_Run2018B",
                                "SKIM_EGamma_Run2018C",
                                "SKIM_EGamma_Run2018D",]
                         },
                2017:{"tauTau":["SKIM_Tau_Run2017B",
                                "SKIM_Tau_Run2017C",
                                "SKIM_Tau_Run2017D",
                                "SKIM_Tau_Run2017E",
                                "SKIM_Tau_Run2017F",],
                      "muTau": ["SKIM_SingleMuon_Run2017B",
                                  "SKIM_SingleMuon_Run2017C",
                                  "SKIM_SingleMuon_Run2017D",
                                  "SKIM_SingleMuon_Run2017E",
                                  "SKIM_SingleMuon_Run2017F",],
                      "eTau": ["SKIM_EGamma_Run2017B",
                               "SKIM_EGamma_Run2017C",
                               "SKIM_EGamma_Run2017D",
                               "SKIM_EGamma_Run2017E",
                               "SKIM_EGamma_Run2017F",]
                     },
                2016:{"tauTau":["SKIM_Tau_Run2016F",
                                "SKIM_Tau_Run2016G",
                                "SKIM_Tau_Run2016H",],
                      "muTau": ["SKIM_Mu_Run2016F",
                                  "SKIM_Mu_Run2016G",
                                  "SKIM_Mu_Run2016H",],
                      "eTau": ["SKIM_Ele_Run2016F",
                               "SKIM_Ele_Run2016G",
                               "SKIM_Ele_Run2016H"]
                     }
                }